"""Initial migration.

Revision ID: 479a62306262
Revises: 
Create Date: 2024-12-19 02:01:03.181112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479a62306262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wilaya', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('date')
        batch_op.drop_column('wilaya')

    # ### end Alembic commands ###
